/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedReferenceWorkUnitsRouteImport } from './routes/_authenticated/reference/work-units'
import { Route as AuthenticatedReferenceRolesRouteImport } from './routes/_authenticated/reference/roles'
import { Route as AuthenticatedReferenceModulesRouteImport } from './routes/_authenticated/reference/modules'
import { Route as AuthenticatedReferenceCurrenciesRouteImport } from './routes/_authenticated/reference/currencies'
import { Route as AuthenticatedReferenceAccountTemplatesRouteImport } from './routes/_authenticated/reference/account-templates'
import { Route as AuthenticatedReferenceAccountMappingsRouteImport } from './routes/_authenticated/reference/account-mappings'
import { Route as AuthenticatedAnalyticsSubscriptionsRouteImport } from './routes/_authenticated/analytics/subscriptions'
import { Route as AuthenticatedAnalyticsOverviewRouteImport } from './routes/_authenticated/analytics/overview'
import { Route as AuthenticatedAnalyticsOrganizationsRouteImport } from './routes/_authenticated/analytics/organizations'
import { Route as AuthenticatedAnalyticsEventsRouteImport } from './routes/_authenticated/analytics/events'
import { Route as AuthenticatedAnalyticsOrganizationsOrgIdRouteImport } from './routes/_authenticated/analytics/organizations.$orgId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferenceWorkUnitsRoute =
  AuthenticatedReferenceWorkUnitsRouteImport.update({
    id: '/reference/work-units',
    path: '/reference/work-units',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferenceRolesRoute =
  AuthenticatedReferenceRolesRouteImport.update({
    id: '/reference/roles',
    path: '/reference/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferenceModulesRoute =
  AuthenticatedReferenceModulesRouteImport.update({
    id: '/reference/modules',
    path: '/reference/modules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferenceCurrenciesRoute =
  AuthenticatedReferenceCurrenciesRouteImport.update({
    id: '/reference/currencies',
    path: '/reference/currencies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferenceAccountTemplatesRoute =
  AuthenticatedReferenceAccountTemplatesRouteImport.update({
    id: '/reference/account-templates',
    path: '/reference/account-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferenceAccountMappingsRoute =
  AuthenticatedReferenceAccountMappingsRouteImport.update({
    id: '/reference/account-mappings',
    path: '/reference/account-mappings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsSubscriptionsRoute =
  AuthenticatedAnalyticsSubscriptionsRouteImport.update({
    id: '/analytics/subscriptions',
    path: '/analytics/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsOverviewRoute =
  AuthenticatedAnalyticsOverviewRouteImport.update({
    id: '/analytics/overview',
    path: '/analytics/overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsOrganizationsRoute =
  AuthenticatedAnalyticsOrganizationsRouteImport.update({
    id: '/analytics/organizations',
    path: '/analytics/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsEventsRoute =
  AuthenticatedAnalyticsEventsRouteImport.update({
    id: '/analytics/events',
    path: '/analytics/events',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsOrganizationsOrgIdRoute =
  AuthenticatedAnalyticsOrganizationsOrgIdRouteImport.update({
    id: '/$orgId',
    path: '/$orgId',
    getParentRoute: () => AuthenticatedAnalyticsOrganizationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/': typeof AuthenticatedIndexRoute
  '/analytics/events': typeof AuthenticatedAnalyticsEventsRoute
  '/analytics/organizations': typeof AuthenticatedAnalyticsOrganizationsRouteWithChildren
  '/analytics/overview': typeof AuthenticatedAnalyticsOverviewRoute
  '/analytics/subscriptions': typeof AuthenticatedAnalyticsSubscriptionsRoute
  '/reference/account-mappings': typeof AuthenticatedReferenceAccountMappingsRoute
  '/reference/account-templates': typeof AuthenticatedReferenceAccountTemplatesRoute
  '/reference/currencies': typeof AuthenticatedReferenceCurrenciesRoute
  '/reference/modules': typeof AuthenticatedReferenceModulesRoute
  '/reference/roles': typeof AuthenticatedReferenceRolesRoute
  '/reference/work-units': typeof AuthenticatedReferenceWorkUnitsRoute
  '/analytics/organizations/$orgId': typeof AuthenticatedAnalyticsOrganizationsOrgIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/': typeof AuthenticatedIndexRoute
  '/analytics/events': typeof AuthenticatedAnalyticsEventsRoute
  '/analytics/organizations': typeof AuthenticatedAnalyticsOrganizationsRouteWithChildren
  '/analytics/overview': typeof AuthenticatedAnalyticsOverviewRoute
  '/analytics/subscriptions': typeof AuthenticatedAnalyticsSubscriptionsRoute
  '/reference/account-mappings': typeof AuthenticatedReferenceAccountMappingsRoute
  '/reference/account-templates': typeof AuthenticatedReferenceAccountTemplatesRoute
  '/reference/currencies': typeof AuthenticatedReferenceCurrenciesRoute
  '/reference/modules': typeof AuthenticatedReferenceModulesRoute
  '/reference/roles': typeof AuthenticatedReferenceRolesRoute
  '/reference/work-units': typeof AuthenticatedReferenceWorkUnitsRoute
  '/analytics/organizations/$orgId': typeof AuthenticatedAnalyticsOrganizationsOrgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/analytics/events': typeof AuthenticatedAnalyticsEventsRoute
  '/_authenticated/analytics/organizations': typeof AuthenticatedAnalyticsOrganizationsRouteWithChildren
  '/_authenticated/analytics/overview': typeof AuthenticatedAnalyticsOverviewRoute
  '/_authenticated/analytics/subscriptions': typeof AuthenticatedAnalyticsSubscriptionsRoute
  '/_authenticated/reference/account-mappings': typeof AuthenticatedReferenceAccountMappingsRoute
  '/_authenticated/reference/account-templates': typeof AuthenticatedReferenceAccountTemplatesRoute
  '/_authenticated/reference/currencies': typeof AuthenticatedReferenceCurrenciesRoute
  '/_authenticated/reference/modules': typeof AuthenticatedReferenceModulesRoute
  '/_authenticated/reference/roles': typeof AuthenticatedReferenceRolesRoute
  '/_authenticated/reference/work-units': typeof AuthenticatedReferenceWorkUnitsRoute
  '/_authenticated/analytics/organizations/$orgId': typeof AuthenticatedAnalyticsOrganizationsOrgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/jobs'
    | '/'
    | '/analytics/events'
    | '/analytics/organizations'
    | '/analytics/overview'
    | '/analytics/subscriptions'
    | '/reference/account-mappings'
    | '/reference/account-templates'
    | '/reference/currencies'
    | '/reference/modules'
    | '/reference/roles'
    | '/reference/work-units'
    | '/analytics/organizations/$orgId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/jobs'
    | '/'
    | '/analytics/events'
    | '/analytics/organizations'
    | '/analytics/overview'
    | '/analytics/subscriptions'
    | '/reference/account-mappings'
    | '/reference/account-templates'
    | '/reference/currencies'
    | '/reference/modules'
    | '/reference/roles'
    | '/reference/work-units'
    | '/analytics/organizations/$orgId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/jobs'
    | '/_authenticated/'
    | '/_authenticated/analytics/events'
    | '/_authenticated/analytics/organizations'
    | '/_authenticated/analytics/overview'
    | '/_authenticated/analytics/subscriptions'
    | '/_authenticated/reference/account-mappings'
    | '/_authenticated/reference/account-templates'
    | '/_authenticated/reference/currencies'
    | '/_authenticated/reference/modules'
    | '/_authenticated/reference/roles'
    | '/_authenticated/reference/work-units'
    | '/_authenticated/analytics/organizations/$orgId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reference/work-units': {
      id: '/_authenticated/reference/work-units'
      path: '/reference/work-units'
      fullPath: '/reference/work-units'
      preLoaderRoute: typeof AuthenticatedReferenceWorkUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reference/roles': {
      id: '/_authenticated/reference/roles'
      path: '/reference/roles'
      fullPath: '/reference/roles'
      preLoaderRoute: typeof AuthenticatedReferenceRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reference/modules': {
      id: '/_authenticated/reference/modules'
      path: '/reference/modules'
      fullPath: '/reference/modules'
      preLoaderRoute: typeof AuthenticatedReferenceModulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reference/currencies': {
      id: '/_authenticated/reference/currencies'
      path: '/reference/currencies'
      fullPath: '/reference/currencies'
      preLoaderRoute: typeof AuthenticatedReferenceCurrenciesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reference/account-templates': {
      id: '/_authenticated/reference/account-templates'
      path: '/reference/account-templates'
      fullPath: '/reference/account-templates'
      preLoaderRoute: typeof AuthenticatedReferenceAccountTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reference/account-mappings': {
      id: '/_authenticated/reference/account-mappings'
      path: '/reference/account-mappings'
      fullPath: '/reference/account-mappings'
      preLoaderRoute: typeof AuthenticatedReferenceAccountMappingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/subscriptions': {
      id: '/_authenticated/analytics/subscriptions'
      path: '/analytics/subscriptions'
      fullPath: '/analytics/subscriptions'
      preLoaderRoute: typeof AuthenticatedAnalyticsSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/overview': {
      id: '/_authenticated/analytics/overview'
      path: '/analytics/overview'
      fullPath: '/analytics/overview'
      preLoaderRoute: typeof AuthenticatedAnalyticsOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/organizations': {
      id: '/_authenticated/analytics/organizations'
      path: '/analytics/organizations'
      fullPath: '/analytics/organizations'
      preLoaderRoute: typeof AuthenticatedAnalyticsOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/events': {
      id: '/_authenticated/analytics/events'
      path: '/analytics/events'
      fullPath: '/analytics/events'
      preLoaderRoute: typeof AuthenticatedAnalyticsEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/organizations/$orgId': {
      id: '/_authenticated/analytics/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/analytics/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedAnalyticsOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedAnalyticsOrganizationsRoute
    }
  }
}

interface AuthenticatedAnalyticsOrganizationsRouteChildren {
  AuthenticatedAnalyticsOrganizationsOrgIdRoute: typeof AuthenticatedAnalyticsOrganizationsOrgIdRoute
}

const AuthenticatedAnalyticsOrganizationsRouteChildren: AuthenticatedAnalyticsOrganizationsRouteChildren =
  {
    AuthenticatedAnalyticsOrganizationsOrgIdRoute:
      AuthenticatedAnalyticsOrganizationsOrgIdRoute,
  }

const AuthenticatedAnalyticsOrganizationsRouteWithChildren =
  AuthenticatedAnalyticsOrganizationsRoute._addFileChildren(
    AuthenticatedAnalyticsOrganizationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnalyticsEventsRoute: typeof AuthenticatedAnalyticsEventsRoute
  AuthenticatedAnalyticsOrganizationsRoute: typeof AuthenticatedAnalyticsOrganizationsRouteWithChildren
  AuthenticatedAnalyticsOverviewRoute: typeof AuthenticatedAnalyticsOverviewRoute
  AuthenticatedAnalyticsSubscriptionsRoute: typeof AuthenticatedAnalyticsSubscriptionsRoute
  AuthenticatedReferenceAccountMappingsRoute: typeof AuthenticatedReferenceAccountMappingsRoute
  AuthenticatedReferenceAccountTemplatesRoute: typeof AuthenticatedReferenceAccountTemplatesRoute
  AuthenticatedReferenceCurrenciesRoute: typeof AuthenticatedReferenceCurrenciesRoute
  AuthenticatedReferenceModulesRoute: typeof AuthenticatedReferenceModulesRoute
  AuthenticatedReferenceRolesRoute: typeof AuthenticatedReferenceRolesRoute
  AuthenticatedReferenceWorkUnitsRoute: typeof AuthenticatedReferenceWorkUnitsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnalyticsEventsRoute: AuthenticatedAnalyticsEventsRoute,
  AuthenticatedAnalyticsOrganizationsRoute:
    AuthenticatedAnalyticsOrganizationsRouteWithChildren,
  AuthenticatedAnalyticsOverviewRoute: AuthenticatedAnalyticsOverviewRoute,
  AuthenticatedAnalyticsSubscriptionsRoute:
    AuthenticatedAnalyticsSubscriptionsRoute,
  AuthenticatedReferenceAccountMappingsRoute:
    AuthenticatedReferenceAccountMappingsRoute,
  AuthenticatedReferenceAccountTemplatesRoute:
    AuthenticatedReferenceAccountTemplatesRoute,
  AuthenticatedReferenceCurrenciesRoute: AuthenticatedReferenceCurrenciesRoute,
  AuthenticatedReferenceModulesRoute: AuthenticatedReferenceModulesRoute,
  AuthenticatedReferenceRolesRoute: AuthenticatedReferenceRolesRoute,
  AuthenticatedReferenceWorkUnitsRoute: AuthenticatedReferenceWorkUnitsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
