/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedRdvRouteImport } from './routes/_authenticated/rdv'
import { Route as AuthenticatedReferentielsCropRouteImport } from './routes/_authenticated/referentiels/$crop'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRdvRoute = AuthenticatedRdvRouteImport.update({
  id: '/rdv',
  path: '/rdv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferentielsCropRoute =
  AuthenticatedReferentielsCropRouteImport.update({
    id: '/referentiels/$crop',
    path: '/referentiels/$crop',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/rdv': typeof AuthenticatedRdvRoute
  '/referentiels/$crop': typeof AuthenticatedReferentielsCropRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/rdv': typeof AuthenticatedRdvRoute
  '/': typeof AuthenticatedIndexRoute
  '/referentiels/$crop': typeof AuthenticatedReferentielsCropRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/rdv': typeof AuthenticatedRdvRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/referentiels/$crop': typeof AuthenticatedReferentielsCropRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/rdv' | '/referentiels/$crop'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/rdv' | '/' | '/referentiels/$crop'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/rdv'
    | '/_authenticated/'
    | '/_authenticated/referentiels/$crop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rdv': {
      id: '/_authenticated/rdv'
      path: '/rdv'
      fullPath: '/rdv'
      preLoaderRoute: typeof AuthenticatedRdvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referentiels/$crop': {
      id: '/_authenticated/referentiels/$crop'
      path: '/referentiels/$crop'
      fullPath: '/referentiels/$crop'
      preLoaderRoute: typeof AuthenticatedReferentielsCropRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedRdvRoute: typeof AuthenticatedRdvRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReferentielsCropRoute: typeof AuthenticatedReferentielsCropRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRdvRoute: AuthenticatedRdvRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReferentielsCropRoute: AuthenticatedReferentielsCropRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
