/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSupportedCountriesRouteImport } from './routes/_authenticated/supported-countries'
import { Route as AuthenticatedSupportSettingsRouteImport } from './routes/_authenticated/support-settings'
import { Route as AuthenticatedSubscriptionModelRouteImport } from './routes/_authenticated/subscription-model'
import { Route as AuthenticatedRdvRouteImport } from './routes/_authenticated/rdv'
import { Route as AuthenticatedRagSourcesRouteImport } from './routes/_authenticated/rag-sources'
import { Route as AuthenticatedModulesRouteImport } from './routes/_authenticated/modules'
import { Route as AuthenticatedLandingSettingsRouteImport } from './routes/_authenticated/landing-settings'
import { Route as AuthenticatedEmailTemplatesRouteImport } from './routes/_authenticated/email-templates'
import { Route as AuthenticatedCronJobsRouteImport } from './routes/_authenticated/cron-jobs'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated/changelog'
import { Route as AuthenticatedBannersRouteImport } from './routes/_authenticated/banners'
import { Route as AuthenticatedAccessControlRouteImport } from './routes/_authenticated/access-control'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedReferentielsCropRouteImport } from './routes/_authenticated/referentiels/$crop'
import { Route as AuthenticatedClientsOrgIdRouteImport } from './routes/_authenticated/clients/$orgId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportedCountriesRoute =
  AuthenticatedSupportedCountriesRouteImport.update({
    id: '/supported-countries',
    path: '/supported-countries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSupportSettingsRoute =
  AuthenticatedSupportSettingsRouteImport.update({
    id: '/support-settings',
    path: '/support-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscriptionModelRoute =
  AuthenticatedSubscriptionModelRouteImport.update({
    id: '/subscription-model',
    path: '/subscription-model',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRdvRoute = AuthenticatedRdvRouteImport.update({
  id: '/rdv',
  path: '/rdv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRagSourcesRoute = AuthenticatedRagSourcesRouteImport.update({
  id: '/rag-sources',
  path: '/rag-sources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModulesRoute = AuthenticatedModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandingSettingsRoute =
  AuthenticatedLandingSettingsRouteImport.update({
    id: '/landing-settings',
    path: '/landing-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmailTemplatesRoute =
  AuthenticatedEmailTemplatesRouteImport.update({
    id: '/email-templates',
    path: '/email-templates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCronJobsRoute = AuthenticatedCronJobsRouteImport.update({
  id: '/cron-jobs',
  path: '/cron-jobs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBannersRoute = AuthenticatedBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccessControlRoute =
  AuthenticatedAccessControlRouteImport.update({
    id: '/access-control',
    path: '/access-control',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferentielsCropRoute =
  AuthenticatedReferentielsCropRouteImport.update({
    id: '/referentiels/$crop',
    path: '/referentiels/$crop',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsOrgIdRoute =
  AuthenticatedClientsOrgIdRouteImport.update({
    id: '/clients/$orgId',
    path: '/clients/$orgId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/cron-jobs': typeof AuthenticatedCronJobsRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/landing-settings': typeof AuthenticatedLandingSettingsRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/rag-sources': typeof AuthenticatedRagSourcesRoute
  '/rdv': typeof AuthenticatedRdvRoute
  '/subscription-model': typeof AuthenticatedSubscriptionModelRoute
  '/support-settings': typeof AuthenticatedSupportSettingsRoute
  '/supported-countries': typeof AuthenticatedSupportedCountriesRoute
  '/clients/$orgId': typeof AuthenticatedClientsOrgIdRoute
  '/referentiels/$crop': typeof AuthenticatedReferentielsCropRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/access-control': typeof AuthenticatedAccessControlRoute
  '/banners': typeof AuthenticatedBannersRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/cron-jobs': typeof AuthenticatedCronJobsRoute
  '/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/landing-settings': typeof AuthenticatedLandingSettingsRoute
  '/modules': typeof AuthenticatedModulesRoute
  '/rag-sources': typeof AuthenticatedRagSourcesRoute
  '/rdv': typeof AuthenticatedRdvRoute
  '/subscription-model': typeof AuthenticatedSubscriptionModelRoute
  '/support-settings': typeof AuthenticatedSupportSettingsRoute
  '/supported-countries': typeof AuthenticatedSupportedCountriesRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$orgId': typeof AuthenticatedClientsOrgIdRoute
  '/referentiels/$crop': typeof AuthenticatedReferentielsCropRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/access-control': typeof AuthenticatedAccessControlRoute
  '/_authenticated/banners': typeof AuthenticatedBannersRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/cron-jobs': typeof AuthenticatedCronJobsRoute
  '/_authenticated/email-templates': typeof AuthenticatedEmailTemplatesRoute
  '/_authenticated/landing-settings': typeof AuthenticatedLandingSettingsRoute
  '/_authenticated/modules': typeof AuthenticatedModulesRoute
  '/_authenticated/rag-sources': typeof AuthenticatedRagSourcesRoute
  '/_authenticated/rdv': typeof AuthenticatedRdvRoute
  '/_authenticated/subscription-model': typeof AuthenticatedSubscriptionModelRoute
  '/_authenticated/support-settings': typeof AuthenticatedSupportSettingsRoute
  '/_authenticated/supported-countries': typeof AuthenticatedSupportedCountriesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$orgId': typeof AuthenticatedClientsOrgIdRoute
  '/_authenticated/referentiels/$crop': typeof AuthenticatedReferentielsCropRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access-control'
    | '/banners'
    | '/changelog'
    | '/cron-jobs'
    | '/email-templates'
    | '/landing-settings'
    | '/modules'
    | '/rag-sources'
    | '/rdv'
    | '/subscription-model'
    | '/support-settings'
    | '/supported-countries'
    | '/clients/$orgId'
    | '/referentiels/$crop'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/access-control'
    | '/banners'
    | '/changelog'
    | '/cron-jobs'
    | '/email-templates'
    | '/landing-settings'
    | '/modules'
    | '/rag-sources'
    | '/rdv'
    | '/subscription-model'
    | '/support-settings'
    | '/supported-countries'
    | '/'
    | '/clients/$orgId'
    | '/referentiels/$crop'
    | '/clients'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/access-control'
    | '/_authenticated/banners'
    | '/_authenticated/changelog'
    | '/_authenticated/cron-jobs'
    | '/_authenticated/email-templates'
    | '/_authenticated/landing-settings'
    | '/_authenticated/modules'
    | '/_authenticated/rag-sources'
    | '/_authenticated/rdv'
    | '/_authenticated/subscription-model'
    | '/_authenticated/support-settings'
    | '/_authenticated/supported-countries'
    | '/_authenticated/'
    | '/_authenticated/clients/$orgId'
    | '/_authenticated/referentiels/$crop'
    | '/_authenticated/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/supported-countries': {
      id: '/_authenticated/supported-countries'
      path: '/supported-countries'
      fullPath: '/supported-countries'
      preLoaderRoute: typeof AuthenticatedSupportedCountriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support-settings': {
      id: '/_authenticated/support-settings'
      path: '/support-settings'
      fullPath: '/support-settings'
      preLoaderRoute: typeof AuthenticatedSupportSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscription-model': {
      id: '/_authenticated/subscription-model'
      path: '/subscription-model'
      fullPath: '/subscription-model'
      preLoaderRoute: typeof AuthenticatedSubscriptionModelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rdv': {
      id: '/_authenticated/rdv'
      path: '/rdv'
      fullPath: '/rdv'
      preLoaderRoute: typeof AuthenticatedRdvRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rag-sources': {
      id: '/_authenticated/rag-sources'
      path: '/rag-sources'
      fullPath: '/rag-sources'
      preLoaderRoute: typeof AuthenticatedRagSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/modules': {
      id: '/_authenticated/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedModulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landing-settings': {
      id: '/_authenticated/landing-settings'
      path: '/landing-settings'
      fullPath: '/landing-settings'
      preLoaderRoute: typeof AuthenticatedLandingSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-templates': {
      id: '/_authenticated/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AuthenticatedEmailTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cron-jobs': {
      id: '/_authenticated/cron-jobs'
      path: '/cron-jobs'
      fullPath: '/cron-jobs'
      preLoaderRoute: typeof AuthenticatedCronJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banners': {
      id: '/_authenticated/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AuthenticatedBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/access-control': {
      id: '/_authenticated/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AuthenticatedAccessControlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referentiels/$crop': {
      id: '/_authenticated/referentiels/$crop'
      path: '/referentiels/$crop'
      fullPath: '/referentiels/$crop'
      preLoaderRoute: typeof AuthenticatedReferentielsCropRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$orgId': {
      id: '/_authenticated/clients/$orgId'
      path: '/clients/$orgId'
      fullPath: '/clients/$orgId'
      preLoaderRoute: typeof AuthenticatedClientsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccessControlRoute: typeof AuthenticatedAccessControlRoute
  AuthenticatedBannersRoute: typeof AuthenticatedBannersRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedCronJobsRoute: typeof AuthenticatedCronJobsRoute
  AuthenticatedEmailTemplatesRoute: typeof AuthenticatedEmailTemplatesRoute
  AuthenticatedLandingSettingsRoute: typeof AuthenticatedLandingSettingsRoute
  AuthenticatedModulesRoute: typeof AuthenticatedModulesRoute
  AuthenticatedRagSourcesRoute: typeof AuthenticatedRagSourcesRoute
  AuthenticatedRdvRoute: typeof AuthenticatedRdvRoute
  AuthenticatedSubscriptionModelRoute: typeof AuthenticatedSubscriptionModelRoute
  AuthenticatedSupportSettingsRoute: typeof AuthenticatedSupportSettingsRoute
  AuthenticatedSupportedCountriesRoute: typeof AuthenticatedSupportedCountriesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsOrgIdRoute: typeof AuthenticatedClientsOrgIdRoute
  AuthenticatedReferentielsCropRoute: typeof AuthenticatedReferentielsCropRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccessControlRoute: AuthenticatedAccessControlRoute,
  AuthenticatedBannersRoute: AuthenticatedBannersRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedCronJobsRoute: AuthenticatedCronJobsRoute,
  AuthenticatedEmailTemplatesRoute: AuthenticatedEmailTemplatesRoute,
  AuthenticatedLandingSettingsRoute: AuthenticatedLandingSettingsRoute,
  AuthenticatedModulesRoute: AuthenticatedModulesRoute,
  AuthenticatedRagSourcesRoute: AuthenticatedRagSourcesRoute,
  AuthenticatedRdvRoute: AuthenticatedRdvRoute,
  AuthenticatedSubscriptionModelRoute: AuthenticatedSubscriptionModelRoute,
  AuthenticatedSupportSettingsRoute: AuthenticatedSupportSettingsRoute,
  AuthenticatedSupportedCountriesRoute: AuthenticatedSupportedCountriesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsOrgIdRoute: AuthenticatedClientsOrgIdRoute,
  AuthenticatedReferentielsCropRoute: AuthenticatedReferentielsCropRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
