version: '3.8'

services:
  # React Frontend
  frontend:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: agritech-frontend
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-https://najvfshknxkwzorlozre.supabase.co}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agritech-frontend.rule=Host(`agritech-dashboard-g6sumg-2b12b9-5-75-154-125.traefik.me`)"
      - "traefik.http.services.agritech-frontend.loadbalancer.server.port=80"
    depends_on:
      - backend-service
    restart: unless-stopped
    networks:
      - agritech-network

  # Backend Service (Satellite + PDF + Data Processing)
  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    container_name: agritech-backend-service
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - GEE_SERVICE_ACCOUNT=${GEE_SERVICE_ACCOUNT}
      - GEE_PRIVATE_KEY=${GEE_PRIVATE_KEY}
      - GEE_PROJECT_ID=${GEE_PROJECT_ID:-sublime-seat-428722-n5}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-AIzaSyDSsY61Uj4QEgrJU9d0xKpq401-vGU8VbI}
      - SUPABASE_URL=${SUPABASE_URL:-http://agritech-supabase-652186-5-75-154-125.traefik.me}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTc1ODQ0NzksImV4cCI6MTg5MzQ1NjAwMCwiaXNzIjoiZG9rcGxveSJ9.fLPJqpGkPZDoJGQEp31ivplmoMF1mD2sSaeSAc_mscQ}
    volumes:
      - satellite-data:/tmp/satellite-data
    restart: unless-stopped
    networks:
      - agritech-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agritech-network:
    driver: bridge

volumes:
  satellite-data: