version: '3.8'

services:
  # React Frontend
  frontend:
    build:
      context: ./project
      dockerfile: Dockerfile
    container_name: agritech-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-https://najvfshknxkwzorlozre.supabase.co}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    depends_on:
      - satellite-service
    restart: unless-stopped
    networks:
      - agritech-network

  # Satellite Indices Service
  satellite-service:
    build:
      context: ./satellite-indices-service
      dockerfile: Dockerfile
    container_name: satellite-indices-service
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - GEE_SERVICE_ACCOUNT=${GEE_SERVICE_ACCOUNT}
      - GEE_PRIVATE_KEY=${GEE_PRIVATE_KEY}
      - GEE_PROJECT_ID=${GEE_PROJECT_ID:-ndvi-460519}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-AIzaSyDSsY61Uj4QEgrJU9d0xKpq401-vGU8VbI}
      - SUPABASE_URL=${SUPABASE_URL:-https://najvfshknxkwzorlozre.supabase.co}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
    volumes:
      - satellite-data:/tmp/satellite-data
    restart: unless-stopped
    networks:
      - agritech-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agritech-network:
    driver: bridge

volumes:
  satellite-data: