-- =====================================================
-- SEED DATA
-- =====================================================
-- Loaded automatically after `supabase db reset`
-- Order matters: roles → work_units → accounts
-- =====================================================

-- \i directives are not supported by supabase db reset.
-- Run manually with psql if needed:
--   \i seed/01_roles.sql
--   \i seed/02_work_units.sql
--   \i seed/03_accounts.sql
