/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as UtilitiesRouteImport } from './routes/utilities'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SoilAnalysisRouteImport } from './routes/soil-analysis'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SelectTrialRouteImport } from './routes/select-trial'
import { Route as SatelliteAnalysisRouteImport } from './routes/satellite-analysis'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportTrialBalanceRouteImport } from './routes/report-trial-balance'
import { Route as ReportProfitLossRouteImport } from './routes/report-profit-loss'
import { Route as ReportBalanceSheetRouteImport } from './routes/report-balance-sheet'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReceptionBatchesRouteImport } from './routes/reception-batches'
import { Route as QualityControlRouteImport } from './routes/quality-control'
import { Route as ProfitabilityRouteImport } from './routes/profitability'
import { Route as ProductionIntelligenceRouteImport } from './routes/production-intelligence'
import { Route as ParcelsRouteImport } from './routes/parcels'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LabServicesRouteImport } from './routes/lab-services'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as HarvestsRouteImport } from './routes/harvests'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FarmHierarchyRouteImport } from './routes/farm-hierarchy'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DayLaborersRouteImport } from './routes/day-laborers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BillingSalesOrdersRouteImport } from './routes/billing-sales-orders'
import { Route as BillingQuotesRouteImport } from './routes/billing-quotes'
import { Route as BillingPurchaseOrdersRouteImport } from './routes/billing-purchase-orders'
import { Route as AnalysesRouteImport } from './routes/analyses'
import { Route as AccountingReportsRouteImport } from './routes/accounting-reports'
import { Route as AccountingPaymentsRouteImport } from './routes/accounting-payments'
import { Route as AccountingJournalRouteImport } from './routes/accounting-journal'
import { Route as AccountingInvoicesRouteImport } from './routes/accounting-invoices'
import { Route as AccountingCustomersRouteImport } from './routes/accounting-customers'
import { Route as AccountingAccountsRouteImport } from './routes/accounting-accounts'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ModuleIdRouteImport } from './routes/$moduleId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as WorkersPieceWorkRouteImport } from './routes/workers.piece-work'
import { Route as TasksCalendarRouteImport } from './routes/tasks.calendar'
import { Route as StockWarehousesRouteImport } from './routes/stock/warehouses'
import { Route as StockSuppliersRouteImport } from './routes/stock/suppliers'
import { Route as StockReportsRouteImport } from './routes/stock/reports'
import { Route as StockReceptionRouteImport } from './routes/stock/reception'
import { Route as StockItemsRouteImport } from './routes/stock/items'
import { Route as StockInventoryRouteImport } from './routes/stock/inventory'
import { Route as StockGroupsRouteImport } from './routes/stock/groups'
import { Route as StockEntriesRouteImport } from './routes/stock/entries'
import { Route as SettingsWorkUnitsRouteImport } from './routes/settings.work-units'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings.subscription'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsOrganizationRouteImport } from './routes/settings.organization'
import { Route as SettingsModulesRouteImport } from './routes/settings.modules'
import { Route as SettingsFilesRouteImport } from './routes/settings.files'
import { Route as SettingsDocumentsRouteImport } from './routes/settings.documents'
import { Route as SettingsDashboardRouteImport } from './routes/settings.dashboard'
import { Route as SettingsDangerZoneRouteImport } from './routes/settings.danger-zone'
import { Route as SettingsCostCentersRouteImport } from './routes/settings.cost-centers'
import { Route as SettingsAccountMappingsRouteImport } from './routes/settings.account-mappings'
import { Route as ParcelsParcelIdRouteImport } from './routes/parcels.$parcelId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as StockInventoryIndexRouteImport } from './routes/stock/inventory/index'
import { Route as ParcelsParcelIdIndexRouteImport } from './routes/parcels.$parcelId.index'
import { Route as StockInventoryStockRouteImport } from './routes/stock/inventory/stock'
import { Route as ParcelsParcelIdWeatherRouteImport } from './routes/parcels.$parcelId.weather'
import { Route as ParcelsParcelIdSatelliteRouteImport } from './routes/parcels.$parcelId.satellite'
import { Route as ParcelsParcelIdReportsRouteImport } from './routes/parcels.$parcelId.reports'
import { Route as ParcelsParcelIdProfitabilityRouteImport } from './routes/parcels.$parcelId.profitability'
import { Route as ParcelsParcelIdProductionRouteImport } from './routes/parcels.$parcelId.production'
import { Route as ParcelsParcelIdAnalyseRouteImport } from './routes/parcels.$parcelId.analyse'

const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesRoute = UtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilAnalysisRoute = SoilAnalysisRouteImport.update({
  id: '/soil-analysis',
  path: '/soil-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTrialRoute = SelectTrialRouteImport.update({
  id: '/select-trial',
  path: '/select-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteAnalysisRoute = SatelliteAnalysisRouteImport.update({
  id: '/satellite-analysis',
  path: '/satellite-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTrialBalanceRoute = ReportTrialBalanceRouteImport.update({
  id: '/report-trial-balance',
  path: '/report-trial-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportProfitLossRoute = ReportProfitLossRouteImport.update({
  id: '/report-profit-loss',
  path: '/report-profit-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportBalanceSheetRoute = ReportBalanceSheetRouteImport.update({
  id: '/report-balance-sheet',
  path: '/report-balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionBatchesRoute = ReceptionBatchesRouteImport.update({
  id: '/reception-batches',
  path: '/reception-batches',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityControlRoute = QualityControlRouteImport.update({
  id: '/quality-control',
  path: '/quality-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitabilityRoute = ProfitabilityRouteImport.update({
  id: '/profitability',
  path: '/profitability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionIntelligenceRoute = ProductionIntelligenceRouteImport.update({
  id: '/production-intelligence',
  path: '/production-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcelsRoute = ParcelsRouteImport.update({
  id: '/parcels',
  path: '/parcels',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LabServicesRoute = LabServicesRouteImport.update({
  id: '/lab-services',
  path: '/lab-services',
  getParentRoute: () => rootRouteImport,
} as any)
const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestsRoute = HarvestsRouteImport.update({
  id: '/harvests',
  path: '/harvests',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmHierarchyRoute = FarmHierarchyRouteImport.update({
  id: '/farm-hierarchy',
  path: '/farm-hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DayLaborersRoute = DayLaborersRouteImport.update({
  id: '/day-laborers',
  path: '/day-laborers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSalesOrdersRoute = BillingSalesOrdersRouteImport.update({
  id: '/billing-sales-orders',
  path: '/billing-sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingQuotesRoute = BillingQuotesRouteImport.update({
  id: '/billing-quotes',
  path: '/billing-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingPurchaseOrdersRoute = BillingPurchaseOrdersRouteImport.update({
  id: '/billing-purchase-orders',
  path: '/billing-purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesRoute = AnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingReportsRoute = AccountingReportsRouteImport.update({
  id: '/accounting-reports',
  path: '/accounting-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingPaymentsRoute = AccountingPaymentsRouteImport.update({
  id: '/accounting-payments',
  path: '/accounting-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingJournalRoute = AccountingJournalRouteImport.update({
  id: '/accounting-journal',
  path: '/accounting-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingInvoicesRoute = AccountingInvoicesRouteImport.update({
  id: '/accounting-invoices',
  path: '/accounting-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingCustomersRoute = AccountingCustomersRouteImport.update({
  id: '/accounting-customers',
  path: '/accounting-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingAccountsRoute = AccountingAccountsRouteImport.update({
  id: '/accounting-accounts',
  path: '/accounting-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleIdRoute = ModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TasksRoute,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const WorkersPieceWorkRoute = WorkersPieceWorkRouteImport.update({
  id: '/piece-work',
  path: '/piece-work',
  getParentRoute: () => WorkersRoute,
} as any)
const TasksCalendarRoute = TasksCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TasksRoute,
} as any)
const StockWarehousesRoute = StockWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => StockRoute,
} as any)
const StockSuppliersRoute = StockSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => StockRoute,
} as any)
const StockReportsRoute = StockReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => StockRoute,
} as any)
const StockReceptionRoute = StockReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => StockRoute,
} as any)
const StockItemsRoute = StockItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => StockRoute,
} as any)
const StockInventoryRoute = StockInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => StockRoute,
} as any)
const StockGroupsRoute = StockGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => StockRoute,
} as any)
const StockEntriesRoute = StockEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => StockRoute,
} as any)
const SettingsWorkUnitsRoute = SettingsWorkUnitsRouteImport.update({
  id: '/work-units',
  path: '/work-units',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsModulesRoute = SettingsModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsFilesRoute = SettingsFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDocumentsRoute = SettingsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDashboardRoute = SettingsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDangerZoneRoute = SettingsDangerZoneRouteImport.update({
  id: '/danger-zone',
  path: '/danger-zone',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCostCentersRoute = SettingsCostCentersRouteImport.update({
  id: '/cost-centers',
  path: '/cost-centers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountMappingsRoute = SettingsAccountMappingsRouteImport.update({
  id: '/account-mappings',
  path: '/account-mappings',
  getParentRoute: () => SettingsRoute,
} as any)
const ParcelsParcelIdRoute = ParcelsParcelIdRouteImport.update({
  id: '/$parcelId',
  path: '/$parcelId',
  getParentRoute: () => ParcelsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StockInventoryIndexRoute = StockInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StockInventoryRoute,
} as any)
const ParcelsParcelIdIndexRoute = ParcelsParcelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParcelsParcelIdRoute,
} as any)
const StockInventoryStockRoute = StockInventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => StockInventoryRoute,
} as any)
const ParcelsParcelIdWeatherRoute = ParcelsParcelIdWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => ParcelsParcelIdRoute,
} as any)
const ParcelsParcelIdSatelliteRoute =
  ParcelsParcelIdSatelliteRouteImport.update({
    id: '/satellite',
    path: '/satellite',
    getParentRoute: () => ParcelsParcelIdRoute,
  } as any)
const ParcelsParcelIdReportsRoute = ParcelsParcelIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ParcelsParcelIdRoute,
} as any)
const ParcelsParcelIdProfitabilityRoute =
  ParcelsParcelIdProfitabilityRouteImport.update({
    id: '/profitability',
    path: '/profitability',
    getParentRoute: () => ParcelsParcelIdRoute,
  } as any)
const ParcelsParcelIdProductionRoute =
  ParcelsParcelIdProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => ParcelsParcelIdRoute,
  } as any)
const ParcelsParcelIdAnalyseRoute = ParcelsParcelIdAnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => ParcelsParcelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$moduleId': typeof ModuleIdRoute
  '/accounting': typeof AccountingRoute
  '/accounting-accounts': typeof AccountingAccountsRoute
  '/accounting-customers': typeof AccountingCustomersRoute
  '/accounting-invoices': typeof AccountingInvoicesRoute
  '/accounting-journal': typeof AccountingJournalRoute
  '/accounting-payments': typeof AccountingPaymentsRoute
  '/accounting-reports': typeof AccountingReportsRoute
  '/analyses': typeof AnalysesRoute
  '/billing-purchase-orders': typeof BillingPurchaseOrdersRoute
  '/billing-quotes': typeof BillingQuotesRoute
  '/billing-sales-orders': typeof BillingSalesOrdersRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout-success': typeof CheckoutSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/day-laborers': typeof DayLaborersRoute
  '/employees': typeof EmployeesRoute
  '/farm-hierarchy': typeof FarmHierarchyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/harvests': typeof HarvestsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/lab-services': typeof LabServicesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/parcels': typeof ParcelsRouteWithChildren
  '/production-intelligence': typeof ProductionIntelligenceRoute
  '/profitability': typeof ProfitabilityRoute
  '/quality-control': typeof QualityControlRoute
  '/reception-batches': typeof ReceptionBatchesRoute
  '/register': typeof RegisterRoute
  '/report-balance-sheet': typeof ReportBalanceSheetRoute
  '/report-profit-loss': typeof ReportProfitLossRoute
  '/report-trial-balance': typeof ReportTrialBalanceRoute
  '/reports': typeof ReportsRoute
  '/satellite-analysis': typeof SatelliteAnalysisRoute
  '/select-trial': typeof SelectTrialRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/soil-analysis': typeof SoilAnalysisRoute
  '/stock': typeof StockRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/utilities': typeof UtilitiesRoute
  '/workers': typeof WorkersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/parcels/$parcelId': typeof ParcelsParcelIdRouteWithChildren
  '/settings/account-mappings': typeof SettingsAccountMappingsRoute
  '/settings/cost-centers': typeof SettingsCostCentersRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/documents': typeof SettingsDocumentsRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/work-units': typeof SettingsWorkUnitsRoute
  '/stock/entries': typeof StockEntriesRoute
  '/stock/groups': typeof StockGroupsRoute
  '/stock/inventory': typeof StockInventoryRouteWithChildren
  '/stock/items': typeof StockItemsRoute
  '/stock/reception': typeof StockReceptionRoute
  '/stock/reports': typeof StockReportsRoute
  '/stock/suppliers': typeof StockSuppliersRoute
  '/stock/warehouses': typeof StockWarehousesRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/workers/piece-work': typeof WorkersPieceWorkRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stock/': typeof StockIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/parcels/$parcelId/analyse': typeof ParcelsParcelIdAnalyseRoute
  '/parcels/$parcelId/production': typeof ParcelsParcelIdProductionRoute
  '/parcels/$parcelId/profitability': typeof ParcelsParcelIdProfitabilityRoute
  '/parcels/$parcelId/reports': typeof ParcelsParcelIdReportsRoute
  '/parcels/$parcelId/satellite': typeof ParcelsParcelIdSatelliteRoute
  '/parcels/$parcelId/weather': typeof ParcelsParcelIdWeatherRoute
  '/stock/inventory/stock': typeof StockInventoryStockRoute
  '/parcels/$parcelId/': typeof ParcelsParcelIdIndexRoute
  '/stock/inventory/': typeof StockInventoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$moduleId': typeof ModuleIdRoute
  '/accounting': typeof AccountingRoute
  '/accounting-accounts': typeof AccountingAccountsRoute
  '/accounting-customers': typeof AccountingCustomersRoute
  '/accounting-invoices': typeof AccountingInvoicesRoute
  '/accounting-journal': typeof AccountingJournalRoute
  '/accounting-payments': typeof AccountingPaymentsRoute
  '/accounting-reports': typeof AccountingReportsRoute
  '/analyses': typeof AnalysesRoute
  '/billing-purchase-orders': typeof BillingPurchaseOrdersRoute
  '/billing-quotes': typeof BillingQuotesRoute
  '/billing-sales-orders': typeof BillingSalesOrdersRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout-success': typeof CheckoutSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/day-laborers': typeof DayLaborersRoute
  '/employees': typeof EmployeesRoute
  '/farm-hierarchy': typeof FarmHierarchyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/harvests': typeof HarvestsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/lab-services': typeof LabServicesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/parcels': typeof ParcelsRouteWithChildren
  '/production-intelligence': typeof ProductionIntelligenceRoute
  '/profitability': typeof ProfitabilityRoute
  '/quality-control': typeof QualityControlRoute
  '/reception-batches': typeof ReceptionBatchesRoute
  '/register': typeof RegisterRoute
  '/report-balance-sheet': typeof ReportBalanceSheetRoute
  '/report-profit-loss': typeof ReportProfitLossRoute
  '/report-trial-balance': typeof ReportTrialBalanceRoute
  '/reports': typeof ReportsRoute
  '/satellite-analysis': typeof SatelliteAnalysisRoute
  '/select-trial': typeof SelectTrialRoute
  '/set-password': typeof SetPasswordRoute
  '/soil-analysis': typeof SoilAnalysisRoute
  '/utilities': typeof UtilitiesRoute
  '/workers': typeof WorkersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/account-mappings': typeof SettingsAccountMappingsRoute
  '/settings/cost-centers': typeof SettingsCostCentersRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/documents': typeof SettingsDocumentsRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/work-units': typeof SettingsWorkUnitsRoute
  '/stock/entries': typeof StockEntriesRoute
  '/stock/groups': typeof StockGroupsRoute
  '/stock/items': typeof StockItemsRoute
  '/stock/reception': typeof StockReceptionRoute
  '/stock/reports': typeof StockReportsRoute
  '/stock/suppliers': typeof StockSuppliersRoute
  '/stock/warehouses': typeof StockWarehousesRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/workers/piece-work': typeof WorkersPieceWorkRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/stock': typeof StockIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/parcels/$parcelId/analyse': typeof ParcelsParcelIdAnalyseRoute
  '/parcels/$parcelId/production': typeof ParcelsParcelIdProductionRoute
  '/parcels/$parcelId/profitability': typeof ParcelsParcelIdProfitabilityRoute
  '/parcels/$parcelId/reports': typeof ParcelsParcelIdReportsRoute
  '/parcels/$parcelId/satellite': typeof ParcelsParcelIdSatelliteRoute
  '/parcels/$parcelId/weather': typeof ParcelsParcelIdWeatherRoute
  '/stock/inventory/stock': typeof StockInventoryStockRoute
  '/parcels/$parcelId': typeof ParcelsParcelIdIndexRoute
  '/stock/inventory': typeof StockInventoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$moduleId': typeof ModuleIdRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/accounting': typeof AccountingRoute
  '/accounting-accounts': typeof AccountingAccountsRoute
  '/accounting-customers': typeof AccountingCustomersRoute
  '/accounting-invoices': typeof AccountingInvoicesRoute
  '/accounting-journal': typeof AccountingJournalRoute
  '/accounting-payments': typeof AccountingPaymentsRoute
  '/accounting-reports': typeof AccountingReportsRoute
  '/analyses': typeof AnalysesRoute
  '/billing-purchase-orders': typeof BillingPurchaseOrdersRoute
  '/billing-quotes': typeof BillingQuotesRoute
  '/billing-sales-orders': typeof BillingSalesOrdersRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout-success': typeof CheckoutSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/day-laborers': typeof DayLaborersRoute
  '/employees': typeof EmployeesRoute
  '/farm-hierarchy': typeof FarmHierarchyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/harvests': typeof HarvestsRoute
  '/infrastructure': typeof InfrastructureRoute
  '/lab-services': typeof LabServicesRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/parcels': typeof ParcelsRouteWithChildren
  '/production-intelligence': typeof ProductionIntelligenceRoute
  '/profitability': typeof ProfitabilityRoute
  '/quality-control': typeof QualityControlRoute
  '/reception-batches': typeof ReceptionBatchesRoute
  '/register': typeof RegisterRoute
  '/report-balance-sheet': typeof ReportBalanceSheetRoute
  '/report-profit-loss': typeof ReportProfitLossRoute
  '/report-trial-balance': typeof ReportTrialBalanceRoute
  '/reports': typeof ReportsRoute
  '/satellite-analysis': typeof SatelliteAnalysisRoute
  '/select-trial': typeof SelectTrialRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/soil-analysis': typeof SoilAnalysisRoute
  '/stock': typeof StockRouteWithChildren
  '/tasks': typeof TasksRouteWithChildren
  '/utilities': typeof UtilitiesRoute
  '/workers': typeof WorkersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/parcels/$parcelId': typeof ParcelsParcelIdRouteWithChildren
  '/settings/account-mappings': typeof SettingsAccountMappingsRoute
  '/settings/cost-centers': typeof SettingsCostCentersRoute
  '/settings/danger-zone': typeof SettingsDangerZoneRoute
  '/settings/dashboard': typeof SettingsDashboardRoute
  '/settings/documents': typeof SettingsDocumentsRoute
  '/settings/files': typeof SettingsFilesRoute
  '/settings/modules': typeof SettingsModulesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/settings/users': typeof SettingsUsersRoute
  '/settings/work-units': typeof SettingsWorkUnitsRoute
  '/stock/entries': typeof StockEntriesRoute
  '/stock/groups': typeof StockGroupsRoute
  '/stock/inventory': typeof StockInventoryRouteWithChildren
  '/stock/items': typeof StockItemsRoute
  '/stock/reception': typeof StockReceptionRoute
  '/stock/reports': typeof StockReportsRoute
  '/stock/suppliers': typeof StockSuppliersRoute
  '/stock/warehouses': typeof StockWarehousesRoute
  '/tasks/calendar': typeof TasksCalendarRoute
  '/workers/piece-work': typeof WorkersPieceWorkRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/stock/': typeof StockIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/parcels/$parcelId/analyse': typeof ParcelsParcelIdAnalyseRoute
  '/parcels/$parcelId/production': typeof ParcelsParcelIdProductionRoute
  '/parcels/$parcelId/profitability': typeof ParcelsParcelIdProfitabilityRoute
  '/parcels/$parcelId/reports': typeof ParcelsParcelIdReportsRoute
  '/parcels/$parcelId/satellite': typeof ParcelsParcelIdSatelliteRoute
  '/parcels/$parcelId/weather': typeof ParcelsParcelIdWeatherRoute
  '/stock/inventory/stock': typeof StockInventoryStockRoute
  '/parcels/$parcelId/': typeof ParcelsParcelIdIndexRoute
  '/stock/inventory/': typeof StockInventoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$moduleId'
    | '/accounting'
    | '/accounting-accounts'
    | '/accounting-customers'
    | '/accounting-invoices'
    | '/accounting-journal'
    | '/accounting-payments'
    | '/accounting-reports'
    | '/analyses'
    | '/billing-purchase-orders'
    | '/billing-quotes'
    | '/billing-sales-orders'
    | '/blog'
    | '/checkout-success'
    | '/dashboard'
    | '/day-laborers'
    | '/employees'
    | '/farm-hierarchy'
    | '/forgot-password'
    | '/harvests'
    | '/infrastructure'
    | '/lab-services'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/parcels'
    | '/production-intelligence'
    | '/profitability'
    | '/quality-control'
    | '/reception-batches'
    | '/register'
    | '/report-balance-sheet'
    | '/report-profit-loss'
    | '/report-trial-balance'
    | '/reports'
    | '/satellite-analysis'
    | '/select-trial'
    | '/set-password'
    | '/settings'
    | '/soil-analysis'
    | '/stock'
    | '/tasks'
    | '/utilities'
    | '/workers'
    | '/auth/callback'
    | '/blog/$slug'
    | '/parcels/$parcelId'
    | '/settings/account-mappings'
    | '/settings/cost-centers'
    | '/settings/danger-zone'
    | '/settings/dashboard'
    | '/settings/documents'
    | '/settings/files'
    | '/settings/modules'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/subscription'
    | '/settings/users'
    | '/settings/work-units'
    | '/stock/entries'
    | '/stock/groups'
    | '/stock/inventory'
    | '/stock/items'
    | '/stock/reception'
    | '/stock/reports'
    | '/stock/suppliers'
    | '/stock/warehouses'
    | '/tasks/calendar'
    | '/workers/piece-work'
    | '/onboarding/'
    | '/settings/'
    | '/stock/'
    | '/tasks/'
    | '/parcels/$parcelId/analyse'
    | '/parcels/$parcelId/production'
    | '/parcels/$parcelId/profitability'
    | '/parcels/$parcelId/reports'
    | '/parcels/$parcelId/satellite'
    | '/parcels/$parcelId/weather'
    | '/stock/inventory/stock'
    | '/parcels/$parcelId/'
    | '/stock/inventory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$moduleId'
    | '/accounting'
    | '/accounting-accounts'
    | '/accounting-customers'
    | '/accounting-invoices'
    | '/accounting-journal'
    | '/accounting-payments'
    | '/accounting-reports'
    | '/analyses'
    | '/billing-purchase-orders'
    | '/billing-quotes'
    | '/billing-sales-orders'
    | '/blog'
    | '/checkout-success'
    | '/dashboard'
    | '/day-laborers'
    | '/employees'
    | '/farm-hierarchy'
    | '/forgot-password'
    | '/harvests'
    | '/infrastructure'
    | '/lab-services'
    | '/login'
    | '/marketplace'
    | '/parcels'
    | '/production-intelligence'
    | '/profitability'
    | '/quality-control'
    | '/reception-batches'
    | '/register'
    | '/report-balance-sheet'
    | '/report-profit-loss'
    | '/report-trial-balance'
    | '/reports'
    | '/satellite-analysis'
    | '/select-trial'
    | '/set-password'
    | '/soil-analysis'
    | '/utilities'
    | '/workers'
    | '/auth/callback'
    | '/blog/$slug'
    | '/settings/account-mappings'
    | '/settings/cost-centers'
    | '/settings/danger-zone'
    | '/settings/dashboard'
    | '/settings/documents'
    | '/settings/files'
    | '/settings/modules'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/subscription'
    | '/settings/users'
    | '/settings/work-units'
    | '/stock/entries'
    | '/stock/groups'
    | '/stock/items'
    | '/stock/reception'
    | '/stock/reports'
    | '/stock/suppliers'
    | '/stock/warehouses'
    | '/tasks/calendar'
    | '/workers/piece-work'
    | '/onboarding'
    | '/settings'
    | '/stock'
    | '/tasks'
    | '/parcels/$parcelId/analyse'
    | '/parcels/$parcelId/production'
    | '/parcels/$parcelId/profitability'
    | '/parcels/$parcelId/reports'
    | '/parcels/$parcelId/satellite'
    | '/parcels/$parcelId/weather'
    | '/stock/inventory/stock'
    | '/parcels/$parcelId'
    | '/stock/inventory'
  id:
    | '__root__'
    | '/'
    | '/$moduleId'
    | '/_authenticated'
    | '/accounting'
    | '/accounting-accounts'
    | '/accounting-customers'
    | '/accounting-invoices'
    | '/accounting-journal'
    | '/accounting-payments'
    | '/accounting-reports'
    | '/analyses'
    | '/billing-purchase-orders'
    | '/billing-quotes'
    | '/billing-sales-orders'
    | '/blog'
    | '/checkout-success'
    | '/dashboard'
    | '/day-laborers'
    | '/employees'
    | '/farm-hierarchy'
    | '/forgot-password'
    | '/harvests'
    | '/infrastructure'
    | '/lab-services'
    | '/login'
    | '/marketplace'
    | '/onboarding'
    | '/parcels'
    | '/production-intelligence'
    | '/profitability'
    | '/quality-control'
    | '/reception-batches'
    | '/register'
    | '/report-balance-sheet'
    | '/report-profit-loss'
    | '/report-trial-balance'
    | '/reports'
    | '/satellite-analysis'
    | '/select-trial'
    | '/set-password'
    | '/settings'
    | '/soil-analysis'
    | '/stock'
    | '/tasks'
    | '/utilities'
    | '/workers'
    | '/auth/callback'
    | '/blog/$slug'
    | '/parcels/$parcelId'
    | '/settings/account-mappings'
    | '/settings/cost-centers'
    | '/settings/danger-zone'
    | '/settings/dashboard'
    | '/settings/documents'
    | '/settings/files'
    | '/settings/modules'
    | '/settings/organization'
    | '/settings/preferences'
    | '/settings/profile'
    | '/settings/subscription'
    | '/settings/users'
    | '/settings/work-units'
    | '/stock/entries'
    | '/stock/groups'
    | '/stock/inventory'
    | '/stock/items'
    | '/stock/reception'
    | '/stock/reports'
    | '/stock/suppliers'
    | '/stock/warehouses'
    | '/tasks/calendar'
    | '/workers/piece-work'
    | '/onboarding/'
    | '/settings/'
    | '/stock/'
    | '/tasks/'
    | '/parcels/$parcelId/analyse'
    | '/parcels/$parcelId/production'
    | '/parcels/$parcelId/profitability'
    | '/parcels/$parcelId/reports'
    | '/parcels/$parcelId/satellite'
    | '/parcels/$parcelId/weather'
    | '/stock/inventory/stock'
    | '/parcels/$parcelId/'
    | '/stock/inventory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuleIdRoute: typeof ModuleIdRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  AccountingRoute: typeof AccountingRoute
  AccountingAccountsRoute: typeof AccountingAccountsRoute
  AccountingCustomersRoute: typeof AccountingCustomersRoute
  AccountingInvoicesRoute: typeof AccountingInvoicesRoute
  AccountingJournalRoute: typeof AccountingJournalRoute
  AccountingPaymentsRoute: typeof AccountingPaymentsRoute
  AccountingReportsRoute: typeof AccountingReportsRoute
  AnalysesRoute: typeof AnalysesRoute
  BillingPurchaseOrdersRoute: typeof BillingPurchaseOrdersRoute
  BillingQuotesRoute: typeof BillingQuotesRoute
  BillingSalesOrdersRoute: typeof BillingSalesOrdersRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DashboardRoute: typeof DashboardRoute
  DayLaborersRoute: typeof DayLaborersRoute
  EmployeesRoute: typeof EmployeesRoute
  FarmHierarchyRoute: typeof FarmHierarchyRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HarvestsRoute: typeof HarvestsRoute
  InfrastructureRoute: typeof InfrastructureRoute
  LabServicesRoute: typeof LabServicesRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ParcelsRoute: typeof ParcelsRouteWithChildren
  ProductionIntelligenceRoute: typeof ProductionIntelligenceRoute
  ProfitabilityRoute: typeof ProfitabilityRoute
  QualityControlRoute: typeof QualityControlRoute
  ReceptionBatchesRoute: typeof ReceptionBatchesRoute
  RegisterRoute: typeof RegisterRoute
  ReportBalanceSheetRoute: typeof ReportBalanceSheetRoute
  ReportProfitLossRoute: typeof ReportProfitLossRoute
  ReportTrialBalanceRoute: typeof ReportTrialBalanceRoute
  ReportsRoute: typeof ReportsRoute
  SatelliteAnalysisRoute: typeof SatelliteAnalysisRoute
  SelectTrialRoute: typeof SelectTrialRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SoilAnalysisRoute: typeof SoilAnalysisRoute
  StockRoute: typeof StockRouteWithChildren
  TasksRoute: typeof TasksRouteWithChildren
  UtilitiesRoute: typeof UtilitiesRoute
  WorkersRoute: typeof WorkersRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities': {
      id: '/utilities'
      path: '/utilities'
      fullPath: '/utilities'
      preLoaderRoute: typeof UtilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil-analysis': {
      id: '/soil-analysis'
      path: '/soil-analysis'
      fullPath: '/soil-analysis'
      preLoaderRoute: typeof SoilAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-trial': {
      id: '/select-trial'
      path: '/select-trial'
      fullPath: '/select-trial'
      preLoaderRoute: typeof SelectTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite-analysis': {
      id: '/satellite-analysis'
      path: '/satellite-analysis'
      fullPath: '/satellite-analysis'
      preLoaderRoute: typeof SatelliteAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-trial-balance': {
      id: '/report-trial-balance'
      path: '/report-trial-balance'
      fullPath: '/report-trial-balance'
      preLoaderRoute: typeof ReportTrialBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-profit-loss': {
      id: '/report-profit-loss'
      path: '/report-profit-loss'
      fullPath: '/report-profit-loss'
      preLoaderRoute: typeof ReportProfitLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-balance-sheet': {
      id: '/report-balance-sheet'
      path: '/report-balance-sheet'
      fullPath: '/report-balance-sheet'
      preLoaderRoute: typeof ReportBalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception-batches': {
      id: '/reception-batches'
      path: '/reception-batches'
      fullPath: '/reception-batches'
      preLoaderRoute: typeof ReceptionBatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-control': {
      id: '/quality-control'
      path: '/quality-control'
      fullPath: '/quality-control'
      preLoaderRoute: typeof QualityControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profitability': {
      id: '/profitability'
      path: '/profitability'
      fullPath: '/profitability'
      preLoaderRoute: typeof ProfitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-intelligence': {
      id: '/production-intelligence'
      path: '/production-intelligence'
      fullPath: '/production-intelligence'
      preLoaderRoute: typeof ProductionIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcels': {
      id: '/parcels'
      path: '/parcels'
      fullPath: '/parcels'
      preLoaderRoute: typeof ParcelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-services': {
      id: '/lab-services'
      path: '/lab-services'
      fullPath: '/lab-services'
      preLoaderRoute: typeof LabServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvests': {
      id: '/harvests'
      path: '/harvests'
      fullPath: '/harvests'
      preLoaderRoute: typeof HarvestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm-hierarchy': {
      id: '/farm-hierarchy'
      path: '/farm-hierarchy'
      fullPath: '/farm-hierarchy'
      preLoaderRoute: typeof FarmHierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-laborers': {
      id: '/day-laborers'
      path: '/day-laborers'
      fullPath: '/day-laborers'
      preLoaderRoute: typeof DayLaborersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-sales-orders': {
      id: '/billing-sales-orders'
      path: '/billing-sales-orders'
      fullPath: '/billing-sales-orders'
      preLoaderRoute: typeof BillingSalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-quotes': {
      id: '/billing-quotes'
      path: '/billing-quotes'
      fullPath: '/billing-quotes'
      preLoaderRoute: typeof BillingQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-purchase-orders': {
      id: '/billing-purchase-orders'
      path: '/billing-purchase-orders'
      fullPath: '/billing-purchase-orders'
      preLoaderRoute: typeof BillingPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses': {
      id: '/analyses'
      path: '/analyses'
      fullPath: '/analyses'
      preLoaderRoute: typeof AnalysesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-reports': {
      id: '/accounting-reports'
      path: '/accounting-reports'
      fullPath: '/accounting-reports'
      preLoaderRoute: typeof AccountingReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-payments': {
      id: '/accounting-payments'
      path: '/accounting-payments'
      fullPath: '/accounting-payments'
      preLoaderRoute: typeof AccountingPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-journal': {
      id: '/accounting-journal'
      path: '/accounting-journal'
      fullPath: '/accounting-journal'
      preLoaderRoute: typeof AccountingJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-invoices': {
      id: '/accounting-invoices'
      path: '/accounting-invoices'
      fullPath: '/accounting-invoices'
      preLoaderRoute: typeof AccountingInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-customers': {
      id: '/accounting-customers'
      path: '/accounting-customers'
      fullPath: '/accounting-customers'
      preLoaderRoute: typeof AccountingCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-accounts': {
      id: '/accounting-accounts'
      path: '/accounting-accounts'
      fullPath: '/accounting-accounts'
      preLoaderRoute: typeof AccountingAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$moduleId': {
      id: '/$moduleId'
      path: '/$moduleId'
      fullPath: '/$moduleId'
      preLoaderRoute: typeof ModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof TasksRoute
    }
    '/stock/': {
      id: '/stock/'
      path: '/'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof StockRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/workers/piece-work': {
      id: '/workers/piece-work'
      path: '/piece-work'
      fullPath: '/workers/piece-work'
      preLoaderRoute: typeof WorkersPieceWorkRouteImport
      parentRoute: typeof WorkersRoute
    }
    '/tasks/calendar': {
      id: '/tasks/calendar'
      path: '/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof TasksCalendarRouteImport
      parentRoute: typeof TasksRoute
    }
    '/stock/warehouses': {
      id: '/stock/warehouses'
      path: '/warehouses'
      fullPath: '/stock/warehouses'
      preLoaderRoute: typeof StockWarehousesRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/suppliers': {
      id: '/stock/suppliers'
      path: '/suppliers'
      fullPath: '/stock/suppliers'
      preLoaderRoute: typeof StockSuppliersRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/reports': {
      id: '/stock/reports'
      path: '/reports'
      fullPath: '/stock/reports'
      preLoaderRoute: typeof StockReportsRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/reception': {
      id: '/stock/reception'
      path: '/reception'
      fullPath: '/stock/reception'
      preLoaderRoute: typeof StockReceptionRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/items': {
      id: '/stock/items'
      path: '/items'
      fullPath: '/stock/items'
      preLoaderRoute: typeof StockItemsRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/inventory': {
      id: '/stock/inventory'
      path: '/inventory'
      fullPath: '/stock/inventory'
      preLoaderRoute: typeof StockInventoryRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/groups': {
      id: '/stock/groups'
      path: '/groups'
      fullPath: '/stock/groups'
      preLoaderRoute: typeof StockGroupsRouteImport
      parentRoute: typeof StockRoute
    }
    '/stock/entries': {
      id: '/stock/entries'
      path: '/entries'
      fullPath: '/stock/entries'
      preLoaderRoute: typeof StockEntriesRouteImport
      parentRoute: typeof StockRoute
    }
    '/settings/work-units': {
      id: '/settings/work-units'
      path: '/work-units'
      fullPath: '/settings/work-units'
      preLoaderRoute: typeof SettingsWorkUnitsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/modules': {
      id: '/settings/modules'
      path: '/modules'
      fullPath: '/settings/modules'
      preLoaderRoute: typeof SettingsModulesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/files': {
      id: '/settings/files'
      path: '/files'
      fullPath: '/settings/files'
      preLoaderRoute: typeof SettingsFilesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/documents': {
      id: '/settings/documents'
      path: '/documents'
      fullPath: '/settings/documents'
      preLoaderRoute: typeof SettingsDocumentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/dashboard': {
      id: '/settings/dashboard'
      path: '/dashboard'
      fullPath: '/settings/dashboard'
      preLoaderRoute: typeof SettingsDashboardRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/danger-zone': {
      id: '/settings/danger-zone'
      path: '/danger-zone'
      fullPath: '/settings/danger-zone'
      preLoaderRoute: typeof SettingsDangerZoneRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/cost-centers': {
      id: '/settings/cost-centers'
      path: '/cost-centers'
      fullPath: '/settings/cost-centers'
      preLoaderRoute: typeof SettingsCostCentersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account-mappings': {
      id: '/settings/account-mappings'
      path: '/account-mappings'
      fullPath: '/settings/account-mappings'
      preLoaderRoute: typeof SettingsAccountMappingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/parcels/$parcelId': {
      id: '/parcels/$parcelId'
      path: '/$parcelId'
      fullPath: '/parcels/$parcelId'
      preLoaderRoute: typeof ParcelsParcelIdRouteImport
      parentRoute: typeof ParcelsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/inventory/': {
      id: '/stock/inventory/'
      path: '/'
      fullPath: '/stock/inventory/'
      preLoaderRoute: typeof StockInventoryIndexRouteImport
      parentRoute: typeof StockInventoryRoute
    }
    '/parcels/$parcelId/': {
      id: '/parcels/$parcelId/'
      path: '/'
      fullPath: '/parcels/$parcelId/'
      preLoaderRoute: typeof ParcelsParcelIdIndexRouteImport
      parentRoute: typeof ParcelsParcelIdRoute
    }
    '/stock/inventory/stock': {
      id: '/stock/inventory/stock'
      path: '/stock'
      fullPath: '/stock/inventory/stock'
      preLoaderRoute: typeof StockInventoryStockRouteImport
      parentRoute: typeof StockInventoryRoute
    }
    '/parcels/$parcelId/weather': {
      id: '/parcels/$parcelId/weather'
      path: '/weather'
      fullPath: '/parcels/$parcelId/weather'
      preLoaderRoute: typeof ParcelsParcelIdWeatherRouteImport
      parentRoute: typeof ParcelsParcelIdRoute
    }
    '/parcels/$parcelId/satellite': {
      id: '/parcels/$parcelId/satellite'
      path: '/satellite'
      fullPath: '/parcels/$parcelId/satellite'
      preLoaderRoute: typeof ParcelsParcelIdSatelliteRouteImport
      parentRoute: typeof ParcelsParcelIdRoute
    }
    '/parcels/$parcelId/reports': {
      id: '/parcels/$parcelId/reports'
      path: '/reports'
      fullPath: '/parcels/$parcelId/reports'
      preLoaderRoute: typeof ParcelsParcelIdReportsRouteImport
      parentRoute: typeof ParcelsParcelIdRoute
    }
    '/parcels/$parcelId/profitability': {
      id: '/parcels/$parcelId/profitability'
      path: '/profitability'
      fullPath: '/parcels/$parcelId/profitability'
      preLoaderRoute: typeof ParcelsParcelIdProfitabilityRouteImport
      parentRoute: typeof ParcelsParcelIdRoute
    }
    '/parcels/$parcelId/production': {
      id: '/parcels/$parcelId/production'
      path: '/production'
      fullPath: '/parcels/$parcelId/production'
      preLoaderRoute: typeof ParcelsParcelIdProductionRouteImport
      parentRoute: typeof ParcelsParcelIdRoute
    }
    '/parcels/$parcelId/analyse': {
      id: '/parcels/$parcelId/analyse'
      path: '/analyse'
      fullPath: '/parcels/$parcelId/analyse'
      preLoaderRoute: typeof ParcelsParcelIdAnalyseRouteImport
      parentRoute: typeof ParcelsParcelIdRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface OnboardingRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface ParcelsParcelIdRouteChildren {
  ParcelsParcelIdAnalyseRoute: typeof ParcelsParcelIdAnalyseRoute
  ParcelsParcelIdProductionRoute: typeof ParcelsParcelIdProductionRoute
  ParcelsParcelIdProfitabilityRoute: typeof ParcelsParcelIdProfitabilityRoute
  ParcelsParcelIdReportsRoute: typeof ParcelsParcelIdReportsRoute
  ParcelsParcelIdSatelliteRoute: typeof ParcelsParcelIdSatelliteRoute
  ParcelsParcelIdWeatherRoute: typeof ParcelsParcelIdWeatherRoute
  ParcelsParcelIdIndexRoute: typeof ParcelsParcelIdIndexRoute
}

const ParcelsParcelIdRouteChildren: ParcelsParcelIdRouteChildren = {
  ParcelsParcelIdAnalyseRoute: ParcelsParcelIdAnalyseRoute,
  ParcelsParcelIdProductionRoute: ParcelsParcelIdProductionRoute,
  ParcelsParcelIdProfitabilityRoute: ParcelsParcelIdProfitabilityRoute,
  ParcelsParcelIdReportsRoute: ParcelsParcelIdReportsRoute,
  ParcelsParcelIdSatelliteRoute: ParcelsParcelIdSatelliteRoute,
  ParcelsParcelIdWeatherRoute: ParcelsParcelIdWeatherRoute,
  ParcelsParcelIdIndexRoute: ParcelsParcelIdIndexRoute,
}

const ParcelsParcelIdRouteWithChildren = ParcelsParcelIdRoute._addFileChildren(
  ParcelsParcelIdRouteChildren,
)

interface ParcelsRouteChildren {
  ParcelsParcelIdRoute: typeof ParcelsParcelIdRouteWithChildren
}

const ParcelsRouteChildren: ParcelsRouteChildren = {
  ParcelsParcelIdRoute: ParcelsParcelIdRouteWithChildren,
}

const ParcelsRouteWithChildren =
  ParcelsRoute._addFileChildren(ParcelsRouteChildren)

interface SettingsRouteChildren {
  SettingsAccountMappingsRoute: typeof SettingsAccountMappingsRoute
  SettingsCostCentersRoute: typeof SettingsCostCentersRoute
  SettingsDangerZoneRoute: typeof SettingsDangerZoneRoute
  SettingsDashboardRoute: typeof SettingsDashboardRoute
  SettingsDocumentsRoute: typeof SettingsDocumentsRoute
  SettingsFilesRoute: typeof SettingsFilesRoute
  SettingsModulesRoute: typeof SettingsModulesRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  SettingsWorkUnitsRoute: typeof SettingsWorkUnitsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountMappingsRoute: SettingsAccountMappingsRoute,
  SettingsCostCentersRoute: SettingsCostCentersRoute,
  SettingsDangerZoneRoute: SettingsDangerZoneRoute,
  SettingsDashboardRoute: SettingsDashboardRoute,
  SettingsDocumentsRoute: SettingsDocumentsRoute,
  SettingsFilesRoute: SettingsFilesRoute,
  SettingsModulesRoute: SettingsModulesRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  SettingsWorkUnitsRoute: SettingsWorkUnitsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface StockInventoryRouteChildren {
  StockInventoryStockRoute: typeof StockInventoryStockRoute
  StockInventoryIndexRoute: typeof StockInventoryIndexRoute
}

const StockInventoryRouteChildren: StockInventoryRouteChildren = {
  StockInventoryStockRoute: StockInventoryStockRoute,
  StockInventoryIndexRoute: StockInventoryIndexRoute,
}

const StockInventoryRouteWithChildren = StockInventoryRoute._addFileChildren(
  StockInventoryRouteChildren,
)

interface StockRouteChildren {
  StockEntriesRoute: typeof StockEntriesRoute
  StockGroupsRoute: typeof StockGroupsRoute
  StockInventoryRoute: typeof StockInventoryRouteWithChildren
  StockItemsRoute: typeof StockItemsRoute
  StockReceptionRoute: typeof StockReceptionRoute
  StockReportsRoute: typeof StockReportsRoute
  StockSuppliersRoute: typeof StockSuppliersRoute
  StockWarehousesRoute: typeof StockWarehousesRoute
  StockIndexRoute: typeof StockIndexRoute
}

const StockRouteChildren: StockRouteChildren = {
  StockEntriesRoute: StockEntriesRoute,
  StockGroupsRoute: StockGroupsRoute,
  StockInventoryRoute: StockInventoryRouteWithChildren,
  StockItemsRoute: StockItemsRoute,
  StockReceptionRoute: StockReceptionRoute,
  StockReportsRoute: StockReportsRoute,
  StockSuppliersRoute: StockSuppliersRoute,
  StockWarehousesRoute: StockWarehousesRoute,
  StockIndexRoute: StockIndexRoute,
}

const StockRouteWithChildren = StockRoute._addFileChildren(StockRouteChildren)

interface TasksRouteChildren {
  TasksCalendarRoute: typeof TasksCalendarRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksCalendarRoute: TasksCalendarRoute,
  TasksIndexRoute: TasksIndexRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

interface WorkersRouteChildren {
  WorkersPieceWorkRoute: typeof WorkersPieceWorkRoute
}

const WorkersRouteChildren: WorkersRouteChildren = {
  WorkersPieceWorkRoute: WorkersPieceWorkRoute,
}

const WorkersRouteWithChildren =
  WorkersRoute._addFileChildren(WorkersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuleIdRoute: ModuleIdRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  AccountingRoute: AccountingRoute,
  AccountingAccountsRoute: AccountingAccountsRoute,
  AccountingCustomersRoute: AccountingCustomersRoute,
  AccountingInvoicesRoute: AccountingInvoicesRoute,
  AccountingJournalRoute: AccountingJournalRoute,
  AccountingPaymentsRoute: AccountingPaymentsRoute,
  AccountingReportsRoute: AccountingReportsRoute,
  AnalysesRoute: AnalysesRoute,
  BillingPurchaseOrdersRoute: BillingPurchaseOrdersRoute,
  BillingQuotesRoute: BillingQuotesRoute,
  BillingSalesOrdersRoute: BillingSalesOrdersRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DashboardRoute: DashboardRoute,
  DayLaborersRoute: DayLaborersRoute,
  EmployeesRoute: EmployeesRoute,
  FarmHierarchyRoute: FarmHierarchyRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HarvestsRoute: HarvestsRoute,
  InfrastructureRoute: InfrastructureRoute,
  LabServicesRoute: LabServicesRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ParcelsRoute: ParcelsRouteWithChildren,
  ProductionIntelligenceRoute: ProductionIntelligenceRoute,
  ProfitabilityRoute: ProfitabilityRoute,
  QualityControlRoute: QualityControlRoute,
  ReceptionBatchesRoute: ReceptionBatchesRoute,
  RegisterRoute: RegisterRoute,
  ReportBalanceSheetRoute: ReportBalanceSheetRoute,
  ReportProfitLossRoute: ReportProfitLossRoute,
  ReportTrialBalanceRoute: ReportTrialBalanceRoute,
  ReportsRoute: ReportsRoute,
  SatelliteAnalysisRoute: SatelliteAnalysisRoute,
  SelectTrialRoute: SelectTrialRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SoilAnalysisRoute: SoilAnalysisRoute,
  StockRoute: StockRouteWithChildren,
  TasksRoute: TasksRouteWithChildren,
  UtilitiesRoute: UtilitiesRoute,
  WorkersRoute: WorkersRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
