version: '3.8'

services:
  satellite-indices-service:
    build: .
    container_name: satellite-indices-service
    environment:
      - DEBUG=false
      - GEE_SERVICE_ACCOUNT=${GEE_SERVICE_ACCOUNT}
      - GEE_PRIVATE_KEY=${GEE_PRIVATE_KEY}
      - GEE_PROJECT_ID=${GEE_PROJECT_ID:-sublime-seat-428722-n5}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-AIzaSyDSsY61Uj4QEgrJU9d0xKpq401-vGU8VbI}
      - SUPABASE_URL=${SUPABASE_URL:-https://agritech-supabase-652186-5-75-154-125.traefik.me}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTc1ODQ0NzksImV4cCI6MTg5MzQ1NjAwMCwiaXNzIjoiZG9rcGxveSJ9.fLPJqpGkPZDoJGQEp31ivplmoMF1mD2sSaeSAc_mscQ}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-${SUPABASE_SERVICE_KEY}}
    volumes:
      - ./temp-data:/tmp/satellite-data
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      # Basic Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"

      # Router configuration for domain
      - "traefik.http.routers.satellite.rule=Host(`agritech-sattelite-mwlyas-415549-5-75-154-125.traefik.me`)"
      - "traefik.http.routers.satellite.entrypoints=websecure"
      - "traefik.http.routers.satellite.tls=true"
      - "traefik.http.routers.satellite.tls.certresolver=letsencrypt"

      # Service configuration
      - "traefik.http.services.satellite.loadbalancer.server.port=8000"

      # Dokploy labels
      - "dokploy=true"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  dokploy-network:
    external: true

volumes:
  temp-data: