import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsDateString,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
} from 'class-validator';

export class CreateRecommendationDto {
  @ApiProperty({ description: 'Parcel ID linked to the recommendation' })
  @IsNotEmpty()
  @IsUUID()
  parcel_id: string;

  @ApiPropertyOptional({ description: 'Calibration ID used to produce the recommendation' })
  @IsOptional()
  @IsUUID()
  calibration_id?: string;

  @ApiProperty({ description: 'Field observation or constat generated by AI' })
  @IsNotEmpty()
  @IsString()
  constat: string;

  @ApiProperty({ description: 'Diagnostic generated by AI' })
  @IsNotEmpty()
  @IsString()
  diagnostic: string;

  @ApiProperty({ description: 'Recommended action to take' })
  @IsNotEmpty()
  @IsString()
  action: string;

  @ApiPropertyOptional({ description: 'Conditions required to apply the recommendation' })
  @IsOptional()
  @IsString()
  conditions?: string;

  @ApiPropertyOptional({ description: 'Suggested follow-up or suivi plan' })
  @IsOptional()
  @IsString()
  suivi?: string;

  @ApiPropertyOptional({ description: 'Crop type associated with the recommendation' })
  @IsOptional()
  @IsString()
  crop_type?: string;

  @ApiPropertyOptional({ description: 'Alert code that triggered the recommendation' })
  @IsOptional()
  @IsString()
  alert_code?: string;

  @ApiPropertyOptional({ description: 'Priority label for the recommendation' })
  @IsOptional()
  @IsString()
  priority?: string;

  @ApiPropertyOptional({ description: 'Start of the recommendation validity window' })
  @IsOptional()
  @IsDateString()
  valid_from?: string;

  @ApiPropertyOptional({ description: 'End of the recommendation validity window' })
  @IsOptional()
  @IsDateString()
  valid_until?: string;
}

export class ExecuteRecommendationDto {
  @ApiPropertyOptional({ description: 'Execution notes recorded when applying the recommendation' })
  @IsOptional()
  @IsString()
  notes?: string;
}
