version: '3.8'

services:
  satellite-indices-service:
    build: .
    container_name: satellite-indices-service
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - GEE_SERVICE_ACCOUNT=${GEE_SERVICE_ACCOUNT}
      - GEE_PRIVATE_KEY=${GEE_PRIVATE_KEY}
      - GEE_PROJECT_ID=${GEE_PROJECT_ID:-sublime-seat-428722-n5}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-AIzaSyDSsY61Uj4QEgrJU9d0xKpq401-vGU8VbI}
      - SUPABASE_URL=${SUPABASE_URL:-http://agritech-supabase-652186-5-75-154-125.traefik.me}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NTc1ODQ0NzksImV4cCI6MTg5MzQ1NjAwMCwiaXNzIjoiZG9rcGxveSJ9.fLPJqpGkPZDoJGQEp31ivplmoMF1mD2sSaeSAc_mscQ}
    volumes:
      - ./temp-data:/tmp/satellite-data
    restart: unless-stopped
    networks:
      - agritech-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  agritech-network:
    driver: bridge

volumes:
  temp-data: