export interface AlertDefinition {
  code: string;
  culture: string;
  severity: "critical" | "high" | "medium" | "low";
  category: string;
  title_en: string;
  title_fr: string;
  title_ar: string;
  requires_immediate_notification: boolean;
}

export const ALERT_TAXONOMY: AlertDefinition[] = [
  {
    code: "OLI-01",
    culture: "olivier",
    severity: "high",
    category: "hydric_stress",
    title_en: "Severe water stress detected",
    title_fr: "Stress hydrique sévère détecté",
    title_ar: "إجهاد مائي حاد",
    requires_immediate_notification: false,
  },
  {
    code: "OLI-02",
    culture: "olivier",
    severity: "medium",
    category: "nutrition",
    title_en: "Nitrogen deficiency suspected",
    title_fr: "Carence en azote suspectée",
    title_ar: "نقص نيتروجين مشتبه",
    requires_immediate_notification: false,
  },
  {
    code: "OLI-03",
    culture: "olivier",
    severity: "high",
    category: "disease",
    title_en: "Eye of peacock risk (Spilocaea oleagina)",
    title_fr: "Risque œil de paon (Spilocaea oleagina)",
    title_ar: "خطر عين الطاووس",
    requires_immediate_notification: false,
  },
  {
    code: "OLI-04",
    culture: "olivier",
    severity: "medium",
    category: "phenology",
    title_en: "Flowering period — reduce irrigation",
    title_fr: "Période de floraison — réduire irrigation",
    title_ar: "فترة الإزهار — تقليل الري",
    requires_immediate_notification: false,
  },
  {
    code: "OLI-05",
    culture: "olivier",
    severity: "low",
    category: "vegetation",
    title_en: "NDVI decline in specific zone",
    title_fr: "Déclin NDVI dans une zone spécifique",
    title_ar: "انخفاض NDVI في منطقة محددة",
    requires_immediate_notification: false,
  },
  {
    code: "OLI-06",
    culture: "olivier",
    severity: "high",
    category: "frost",
    title_en: "Frost damage risk",
    title_fr: "Risque de dégâts de gel",
    title_ar: "خطر أضرار الصقيع",
    requires_immediate_notification: true,
  },

  {
    code: "AGR-01",
    culture: "agrumes",
    severity: "high",
    category: "hydric_stress",
    title_en: "Severe water stress on citrus",
    title_fr: "Stress hydrique sévère sur agrumes",
    title_ar: "إجهاد مائي حاد على الحوامض",
    requires_immediate_notification: false,
  },
  {
    code: "AGR-02",
    culture: "agrumes",
    severity: "high",
    category: "disease",
    title_en: "Citrus tristeza risk",
    title_fr: "Risque de tristeza des agrumes",
    title_ar: "خطر تريستيزا الحوامض",
    requires_immediate_notification: true,
  },
  {
    code: "AGR-03",
    culture: "agrumes",
    severity: "medium",
    category: "nutrition",
    title_en: "Iron chlorosis detected",
    title_fr: "Chlorose ferrique détectée",
    title_ar: "كلوروز حديدي",
    requires_immediate_notification: false,
  },
  {
    code: "AGR-04",
    culture: "agrumes",
    severity: "medium",
    category: "pest",
    title_en: "Citrus leafminer activity",
    title_fr: "Activité mineuse des agrumes",
    title_ar: "نشاط حافرة أوراق الحوامض",
    requires_immediate_notification: false,
  },
  {
    code: "AGR-05",
    culture: "agrumes",
    severity: "high",
    category: "frost",
    title_en: "Frost risk on citrus",
    title_fr: "Risque de gel sur agrumes",
    title_ar: "خطر الصقيع على الحوامض",
    requires_immediate_notification: true,
  },
  {
    code: "AGR-06",
    culture: "agrumes",
    severity: "medium",
    category: "salinity",
    title_en: "Salt stress detected",
    title_fr: "Stress salin détecté",
    title_ar: "إجهاد ملحي",
    requires_immediate_notification: false,
  },
  {
    code: "AGR-07",
    culture: "agrumes",
    severity: "critical",
    category: "disease",
    title_en: "Phytophthora root rot suspected",
    title_fr: "Phytophthora racinaire suspecté",
    title_ar: "تعفن جذري فيتوفثورا مشتبه",
    requires_immediate_notification: true,
  },
  {
    code: "AGR-08",
    culture: "agrumes",
    severity: "critical",
    category: "disease",
    title_en: "HLB/Greening risk indicators",
    title_fr: "Indicateurs de risque HLB/Greening",
    title_ar: "مؤشرات خطر مرض الاخضرار",
    requires_immediate_notification: true,
  },

  {
    code: "AVO-01",
    culture: "avocatier",
    severity: "high",
    category: "hydric_stress",
    title_en: "Severe water stress on avocado",
    title_fr: "Stress hydrique sévère sur avocatier",
    title_ar: "إجهاد مائي حاد على الأفوكادو",
    requires_immediate_notification: false,
  },
  {
    code: "AVO-02",
    culture: "avocatier",
    severity: "medium",
    category: "nutrition",
    title_en: "Zinc or boron deficiency suspected",
    title_fr: "Carence en zinc ou bore suspectée",
    title_ar: "نقص زنك أو بورون مشتبه",
    requires_immediate_notification: false,
  },
  {
    code: "AVO-03",
    culture: "avocatier",
    severity: "high",
    category: "salinity",
    title_en: "Chloride toxicity risk",
    title_fr: "Risque de toxicité chlorures",
    title_ar: "خطر سمية الكلوريد",
    requires_immediate_notification: false,
  },
  {
    code: "AVO-04",
    culture: "avocatier",
    severity: "medium",
    category: "vegetation",
    title_en: "Canopy decline detected",
    title_fr: "Déclin de canopée détecté",
    title_ar: "انخفاض في المظلة الورقية",
    requires_immediate_notification: false,
  },
  {
    code: "AVO-05",
    culture: "avocatier",
    severity: "critical",
    category: "frost",
    title_en: "Critical frost damage on avocado",
    title_fr: "Dégâts de gel critique sur avocatier",
    title_ar: "أضرار صقيع حرجة على الأفوكادو",
    requires_immediate_notification: true,
  },
  {
    code: "AVO-06",
    culture: "avocatier",
    severity: "medium",
    category: "disease",
    title_en: "Anthracnose risk (fruit)",
    title_fr: "Risque anthracnose (fruits)",
    title_ar: "خطر أنثراكنوز (ثمار)",
    requires_immediate_notification: false,
  },
  {
    code: "AVO-07",
    culture: "avocatier",
    severity: "critical",
    category: "disease",
    title_en: "Phytophthora root rot suspected",
    title_fr: "Phytophthora racinaire suspecté",
    title_ar: "تعفن جذري فيتوفثورا مشتبه",
    requires_immediate_notification: true,
  },
  {
    code: "AVO-08",
    culture: "avocatier",
    severity: "critical",
    category: "disease",
    title_en: "Avocado sunblotch viroid (ASBVd) indicators",
    title_fr: "Indicateurs viroïde sunblotch avocatier",
    title_ar: "مؤشرات فيرويد صنبلوتش الأفوكادو",
    requires_immediate_notification: true,
  },

  {
    code: "PAL-01",
    culture: "palmier_dattier",
    severity: "high",
    category: "hydric_stress",
    title_en: "Water stress on date palm",
    title_fr: "Stress hydrique sur palmier dattier",
    title_ar: "إجهاد مائي على النخيل",
    requires_immediate_notification: false,
  },
  {
    code: "PAL-02",
    culture: "palmier_dattier",
    severity: "medium",
    category: "nutrition",
    title_en: "Potassium deficiency suspected",
    title_fr: "Carence en potassium suspectée",
    title_ar: "نقص بوتاسيوم مشتبه",
    requires_immediate_notification: false,
  },
  {
    code: "PAL-03",
    culture: "palmier_dattier",
    severity: "medium",
    category: "pest",
    title_en: "Red palm weevil risk",
    title_fr: "Risque charançon rouge",
    title_ar: "خطر سوسة النخيل الحمراء",
    requires_immediate_notification: true,
  },
  {
    code: "PAL-04",
    culture: "palmier_dattier",
    severity: "medium",
    category: "phenology",
    title_en: "Pollination window approaching",
    title_fr: "Période de pollinisation approche",
    title_ar: "اقتراب فترة التلقيح",
    requires_immediate_notification: false,
  },
  {
    code: "PAL-05",
    culture: "palmier_dattier",
    severity: "high",
    category: "salinity",
    title_en: "Soil salinity buildup",
    title_fr: "Accumulation de salinité du sol",
    title_ar: "تراكم ملوحة التربة",
    requires_immediate_notification: false,
  },
  {
    code: "PAL-06",
    culture: "palmier_dattier",
    severity: "medium",
    category: "disease",
    title_en: "Black scorch (Thielaviopsis)",
    title_fr: "Maladie du cœur noir (Thielaviopsis)",
    title_ar: "مرض القلب الأسود",
    requires_immediate_notification: false,
  },
  {
    code: "PAL-07",
    culture: "palmier_dattier",
    severity: "low",
    category: "vegetation",
    title_en: "Frond decline pattern",
    title_fr: "Pattern de déclin des palmes",
    title_ar: "نمط تراجع السعف",
    requires_immediate_notification: false,
  },
  {
    code: "PAL-08",
    culture: "palmier_dattier",
    severity: "critical",
    category: "disease",
    title_en: "Bayoud disease (Fusarium oxysporum f.sp. albedinis)",
    title_fr: "Maladie du Bayoud (Fusarium oxysporum)",
    title_ar: "مرض البيوض (فيوزاريوم)",
    requires_immediate_notification: true,
  },
  {
    code: "PAL-09",
    culture: "palmier_dattier",
    severity: "critical",
    category: "disease",
    title_en: "Bayoud confirmed — quarantine required",
    title_fr: "Bayoud confirmé — quarantaine requise",
    title_ar: "بيوض مؤكد — حجر صحي مطلوب",
    requires_immediate_notification: true,
  },
];

export function getAlertsForCulture(cultureKey: string): AlertDefinition[] {
  return ALERT_TAXONOMY.filter((a) => a.culture === cultureKey);
}

export function getCriticalAlerts(): AlertDefinition[] {
  return ALERT_TAXONOMY.filter((a) => a.requires_immediate_notification);
}
